"""Shared constants for Self-Authored Contract arm."""

from __future__ import annotations

CONTRACTS_DIR = "contracts"
FACTS_FILE = "RUNTIME_FACTS.md"
RUNTIME_DIR = "runtime_traces"
MANIFEST_FILE = "CONTRACT_MANIFEST.json"
LOCK_FILE = "contracts.lock"
AUDIT_FILE = "self_contract_phase.json"
AUTHOR_FAILURES = "AUTHOR_GATE_FAILURES.md"
CONTRACT_FAILURES = "CONTRACT_FAILURES.md"

DEFAULT_MIN_TESTS = 5
DEFAULT_AUTHOR_REPAIR_ROUNDS = 1
DEFAULT_IMPL_REPAIR_ROUNDS = 1
DEFAULT_REPAIR_TIMEOUT_SECONDS = 1800
DEFAULT_AUTHOR_TIMEOUT_SECONDS = 2400

SELF_CONTRACT_ENV = "FEATURELIFTBENCH_SELF_CONTRACT"
SELF_CONTRACT_PHASE_ENV = "FEATURELIFTBENCH_SELF_CONTRACT_PHASE"
